# Updated for new GPU - 2026-03-12
# DP-1: ASUS PG32UCDM (main, left, landscape)
# DP-2: Gigabyte M32U (secondary, right, portrait)

monitor=DP-1,3840x2160@240.0,0x1200,1.25
monitor=DP-2,3840x2160@144.0,3072x0,1.0
monitor=DP-2,transform,3
