#hypridle.conf
general {
    lock_cmd = pidof hyprlock || hyprlock --immediate-render --no-fade-in       # avoid starting multiple hyprlock instances.
    before_sleep_cmd = pidof hyprlock || hyprlock --immediate-render --no-fade-in    # lock before suspend.
  # to avoid having to press a key twice to turn on the display.
}

listener {
    timeout = 300                           # 5min
    on-timeout = pidof hyprlock || hyprlock --immediate-render --no-fade-in                   # command to run when timeout has passed
    on-resume = notify-send "Welcome back!" # command to run when activity is detected after timeout has fired.
}

listener {
    timeout = 380                           # 5.5min
    on-timeout = hyprctl --instance 0 dispatch 'hl.dsp.dpms({ action = "off" })'  # command to run when timeout has passed
    on-resume = hyprctl --instance 0 dispatch 'hl.dsp.dpms({ action = "on" })'    # command to run when activity is detected after timeout has fired.
}

listener {
    timeout = 600              
    on-timeout = systemctl suspend
}
